const tigrigna_description = {
  Sunny: "ፃሓያማ",
  "clear sky": "ንፁህ ሰማይ",
  "overcast clouds": "ብዙሕ ደበና",
  "few clouds": "ውሕድ ደበና",
  "scattered clouds": "ዝተበተነ ደበናታት",
  "broken clouds": "ክፋል ደበናማ",
  "shower rain": "ካፋ",
  rain: "ዝናባማ",
  thunderstorm: "ነጎዳ",
  snow: "በረድ",
  mist: "ግመ",
  fog: "ግመ",
  "light snow": "ቀሊል በረድ",
  "light rain": "ቀሊል ዝናብ",
  "moderate rain": "ማእከላይ ዝናብ",
  "heavy intensity rain": "ከቢድ ዝናብ",
  "very heavy rain": "ብጣዕሚ ከቢድ ዝናብ",
  "freezing rain": "ቆሪር ዝናብ",
  "moderate snow": "ማእከላይ በረድ",
  "heavy snow": "ከቢድ በረድ",
  sleet: "በረድ ዝተሓወሶ ዝናብ",
  "snow shower": "ካፋ በረድ",
  "thunderstorm with rain": "ነጎዳ ዝተሓወሶ ዝናብ",
  "thunderstorm with snow": "ነጎዳ ዝተሓወሶ በረድ",
  "thunderstorm with drizzle": "ነጎዳ ዝተሓወሶ ዝናብ",
  "light intensity drizzle": "ቀሊል ንፋስ",
  drizzle: "ንፋስ ዝተሓወሶ ዝናብ",
  "heavy intensity drizzle": "ከቢድ ንፋስ",
  "tropical storm": "ኣውሎ ንፋስ",
  dust: "ኣቮራ",
  sand: "ኣቮራ",
  tornado: "ከቢድ ንፋስ",
  hurricane: "ሆቦብላ ንፋስ",
};

export default tigrigna_description;
